import {
  Type, ArrowLeftRight, Binary, Sparkles, Globe, Code2, Calculator, Image,
  CaseSensitive, CaseUpper, AlignLeft, FlipHorizontal, Ruler, Hash, Palette,
  Link, FileCode, KeyRound, Fingerprint, QrCode, Braces, FileText, ShieldCheck,
  KeySquare, Percent, Sigma, ImagePlus, FileImage, ScanLine, Crop, Eraser,
  Wand2, Layers, FileType, Merge, Split, FileSearch, TrendingUp,
  DollarSign, PiggyBank, Receipt, BarChart3, Activity, HeartPulse, Timer,
  Scale, Thermometer, Gauge, Repeat, Rss, Bookmark, Mail, MessageSquare,
  Share2, AtSign, Eye, Scan, Bug, Flag, Clock, Flame, Star, Zap, Shield,
  Lock, Unlock, Search, Wrench, Shuffle, FileDiff, GitCompare, ClipboardList,
  Calendar, MapPin, Phone, Printer, Camera, Music, Video, Volume2, Headphones,
  Film, Mic, Languages, BookOpen, GraduationCap, Pencil,
  PenLine, Trash2, Clipboard, ClipboardCheck, FileDown,
  FileUp, Download, Upload, RefreshCw, Repeat2, Maximize2, Minimize2, ZoomIn,
  ZoomOut, RotateCw, RotateCcw, Move, Pipette, Brush, SprayCan, Frame, Grid3x3,
  Grid2x2, Layout, LayoutGrid, Sidebar, PanelTop, PanelsTopLeft, Monitor,
  Smartphone, Tablet, Watch, Tv, Gamepad2, Joystick, Rocket, Satellite, Plane,
  Car, Bike, Bus, Train, Ship, Anchor, Compass, Map, Navigation, Route,
  TreePine, Mountain, Sun, Moon as MoonIcon, Cloud, CloudRain, CloudSnow,
  CloudLightning, Snowflake, Umbrella, Wind, Droplet, Droplets, Waves,
  Battery, BatteryCharging, Plug, Zap as ZapIcon, Lightbulb, HardDrive,
  Bell, BellRing, AlarmClock, Hourglass, CalendarClock, CalendarDays,
  CalendarCheck, CalendarPlus, CalendarX, MailCheck, MailOpen, MailWarning,
  Send, Forward, Reply, ReplyAll, Inbox, Archive, Trash, Folder,
  FolderOpen, FolderPlus, FilePlus, FileMinus, FileCheck, FileX, FileWarning,
  FileLock, FileKey, FileSignature, FileSpreadsheet, FileBarChart, FileBarChart2,
  Files, FileArchive, FileCode2, Terminal,
  Square, SquareCode, SquareStack, Boxes, Package, PackageOpen, PackagePlus,
  PackageCheck, PackageX, Tag, Tags, BookmarkCheck, Ticket, TicketPercent,
  ShoppingCart, ShoppingBag, Store, CreditCard, Wallet, Banknote, Coins,
  CircleDollarSign, BadgeDollarSign, ReceiptText,
  ScrollText, Stamp, Award, Trophy, Medal, Crown, Gem, Diamond, Sparkle,
  Sparkles as SparklesIcon, Star as StarIcon, StarOff, Heart, ThumbsUp,
  ThumbsDown, Hand, HandHeart, HandCoins, Handshake, Smile, Frown, Meh, Laugh,
  Angry, Eye as EyeIcon, EyeOff, View, Focus, Telescope, Microscope,
  FlaskConical, Beaker, TestTube, Dna, Atom, Radiation, Biohazard,
  Skull, Cross, Plus, Minus, X as XIcon, Check, ChevronRight,
  ChevronLeft, ChevronUp, ChevronDown, ChevronsRight, ChevronsLeft, ChevronsUp,
  ChevronsDown, ArrowRight, ArrowLeft, ArrowUp, ArrowDown, ArrowUpRight,
  ArrowDownRight, ArrowUpLeft, ArrowDownLeft, ArrowRightLeft,
  ArrowLeftRight as ArrowLeftRightIcon, MoveRight, MoveLeft, MoveUp, MoveDown,
  CornerDownLeft, CornerDownRight, CornerUpLeft, CornerUpRight, ExternalLink,
  Twitter as TwitterIcon,
  Instagram,
  Facebook,
  Youtube,
  Music2,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  Type, ArrowLeftRight, Binary, Sparkles, Globe, Code2, Calculator, Image,
  CaseSensitive, CaseUpper, AlignLeft, FlipHorizontal, Ruler, Hash, Palette,
  Link, FileCode, KeyRound, Fingerprint, QrCode, Braces, FileText, ShieldCheck,
  KeySquare, Percent, Sigma, ImagePlus, FileImage, ScanLine, Crop, Eraser,
  Wand2, Layers, FileType, Merge, Split, FileSearch, TrendingUp,
  DollarSign, PiggyBank, Receipt, BarChart3, Activity, HeartPulse, Timer,
  Scale, Thermometer, Gauge, Repeat, Rss, Bookmark, Mail, MessageSquare,
  Share2, AtSign, Eye, Scan, Bug, Flag, Clock, Flame, Star, Zap, Shield,
  Lock, Unlock, Search, Wrench, Shuffle, FileDiff, GitCompare, ClipboardList,
  Calendar, MapPin, Phone, Printer, Camera, Music, Video, Volume2, Headphones,
  Film, Mic, Languages, BookOpen, GraduationCap, Pencil, PenLine, Trash2,
  Clipboard, ClipboardCheck, FileDown, FileUp, Download, Upload, RefreshCw,
  Repeat2, Maximize2, Minimize2, ZoomIn, ZoomOut, RotateCw, RotateCcw, Move,
  Pipette, Brush, SprayCan, Frame, Grid3x3, Grid2x2, Layout, LayoutGrid,
  Sidebar, PanelTop, PanelsTopLeft, Monitor, Smartphone, Tablet, Watch, Tv,
  Gamepad2, Joystick, Rocket, Satellite, Plane, Car, Bike, Bus, Train, Ship,
  Anchor, Compass, Map, Navigation, Route, TreePine, Mountain, Sun, MoonIcon,
  Cloud, CloudRain, CloudSnow, CloudLightning, Snowflake, Umbrella, Wind,
  Droplet, Droplets, Waves, Battery, BatteryCharging, Plug, ZapIcon, Lightbulb,
  HardDrive, Bell, BellRing, AlarmClock, Hourglass, CalendarClock, CalendarDays,
  CalendarCheck, CalendarPlus, CalendarX, MailCheck, MailOpen, MailWarning,
  Send, Forward, Reply, ReplyAll, Inbox, Archive, Trash, Folder, FolderOpen,
  FolderPlus, FilePlus, FileMinus, FileCheck, FileX, FileWarning, FileLock,
  FileKey, FileSignature, FileSpreadsheet, FileBarChart, FileBarChart2, Files,
  FileArchive, FileCode2, Terminal, Square, SquareCode, SquareStack, Boxes,
  Package, PackageOpen, PackagePlus, PackageCheck, PackageX, Tag, Tags,
  BookmarkCheck, Ticket, TicketPercent, ShoppingCart, ShoppingBag, Store,
  CreditCard, Wallet, Banknote, Coins, CircleDollarSign, BadgeDollarSign,
  ReceiptText, ScrollText, Stamp, Award, Trophy, Medal, Crown, Gem, Diamond,
  Sparkle, SparklesIcon, StarIcon, StarOff, Heart, ThumbsUp, ThumbsDown, Hand,
  HandHeart, HandCoins, Handshake, Smile, Frown, Meh, Laugh, Angry, EyeIcon,
  EyeOff, View, Focus, Telescope, Microscope, FlaskConical, Beaker, TestTube,
  Dna, Atom, Radiation, Biohazard, Skull, Cross, Plus, Minus, XIcon, Check,
  ChevronRight, ChevronLeft, ChevronUp, ChevronDown, ChevronsRight,
  ChevronsLeft, ChevronsUp, ChevronsDown, ArrowRight, ArrowLeft, ArrowUp,
  ArrowDown, ArrowUpRight, ArrowDownRight, ArrowUpLeft, ArrowDownLeft,
  ArrowRightLeft, ArrowLeftRightIcon, MoveRight, MoveLeft, MoveUp, MoveDown,
  CornerDownLeft, CornerDownRight, CornerUpLeft, CornerUpRight, ExternalLink,
  TwitterIcon, Instagram, Facebook, Youtube, Music2,
};

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? Sparkles;
}
