import { useParams } from "react-router-dom";
import { StaticPage } from "@/components/StaticPage";

const CONTENT: Record<string,{title:string,subtitle:string,sections:{h:string,p:string}[]}>={
 disclaimer:{title:"Disclaimer",subtitle:"Important information about ZidroTool and its online utilities.",sections:[{h:"General information",p:"ZidroTool provides browser-based utilities for convenience and general informational purposes. Results should be reviewed before being used for business, legal, financial or other consequential decisions."},{h:"Third-party services",p:"Some integrations may depend on browser APIs or third-party platforms. Availability and behavior can change outside ZidroTool's control."}]},
 dmca:{title:"DMCA & Copyright",subtitle:"How to report copyright concerns or suspected infringement.",sections:[{h:"Notice",p:"If you believe content hosted by ZidroTool infringes your copyright, send a detailed notice identifying the copyrighted work, the material at issue and your contact information to the site's legal contact."},{h:"Good-faith requests",p:"Please provide enough information for the team to locate and review the reported material. False or incomplete notices may delay review."}]},
 security:{title:"Security",subtitle:"Security practices and responsible disclosure.",sections:[{h:"Browser-first processing",p:"Where supported, file utilities process content locally in the browser so files do not need to be uploaded to ZidroTool servers."},{h:"Report a vulnerability",p:"If you discover a security issue, report it privately through the contact information listed on the Contact page. Do not publicly disclose an exploitable issue before it can be reviewed."}]},
 accessibility:{title:"Accessibility",subtitle:"Our commitment to a usable and accessible website.",sections:[{h:"Accessible interface",p:"ZidroTool aims to provide keyboard-friendly controls, readable contrast, semantic headings, responsive layouts and clear focus states."},{h:"Feedback",p:"If a page or tool is difficult to use with assistive technology, please contact us with the URL and a description of the problem so it can be investigated."}]},
};
export default function TrustPage(){const {slug="disclaimer"}=useParams();const c=CONTENT[slug]||CONTENT.disclaimer;return <StaticPage title={c.title} subtitle={c.subtitle} updated="Last updated: August 2026" breadcrumbs={[{label:c.title}]}>{c.sections.map(s=><section key={s.h}><h2>{s.h}</h2><p>{s.p}</p></section>)}</StaticPage>}
