import { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { useParams } from "react-router-dom";
import { ToolIO } from "@/components/ToolIO";
import { cn } from "@/lib/utils";
import { getTool } from "@/data/catalog";

function escapeSvgText(value: string) { return value.replace(/[<>&"']/g, "-"); }
function summarize(input: string) { const s=input.replace(/\s+/g," ").trim().split(/(?<=[.!?])\s+/).filter(Boolean); if(!s.length)return ""; const n=Math.max(1,Math.min(8,Math.ceil(s.length*.35))); return s.slice(0,n).map(x=>`• ${x}`).join("\n"); }
function grammarCheck(input: string) { return input.replace(/[ \t]+/g," ").replace(/\s+([,.;:!?])/g,"$1").replace(/(^|[.!?]\s+)([a-z])/g,(_,a,b)=>a+b.toUpperCase()).trim(); }
function rewriteContent(input: string) { return input.replace(/\b(utilize|utilizes|utilized)\b/gi,"use").replace(/\b(purchase|purchased|purchasing)\b/gi,"buying").replace(/\b(approximately)\b/gi,"about").replace(/\bin order to\b/gi,"to").replace(/\bdue to the fact that\b/gi,"because"); }
function explainCode(input: string) { const lines=input.split(/\r?\n/), nonEmpty=lines.filter(x=>x.trim()), matches=input.match(/\b(function|const|let|var|class|def|fn)\b/g)||[]; const language=/<\/?[a-z][^>]*>/i.test(input)?"HTML":/\b(interface|type|tsx|React|useState|useEffect)\b/.test(input)?"TypeScript / React":/\b(import|export|const|let|function)\b/.test(input)?"JavaScript":/\b(def|print\(|elif|None|pip)\b/.test(input)?"Python":"Code snippet"; return [`Detected language: ${language}`,`Lines: ${lines.length}`,`Non-empty lines: ${nonEmpty.length}`,`Declarations / functions detected: ${matches.length}`,"","What this local analyzer can do:","• Identify common code patterns and estimate structure.","• Provide quick metrics without uploading your code.","• Keep processing in the browser.","","For deep semantic explanations, connect an AI provider in a future ZidroTool release."].join("\n"); }
function headlineGenerator(input: string) { return input.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).slice(0,10).map(x=>`How to ${x}: A Practical Guide`).join("\n"); }
function ideaGenerator(input: string) { if(!input.trim())return ""; return [`Beginner guide: ${input}`,`Common mistakes when working with ${input}`,`Practical checklist for ${input}`,`Advanced tips for improving ${input}`,`Comparison of popular ${input} methods`].join("\n"); }
function validateRedirectUrl(input: string) { try { const u=new URL(input.trim()); return ["✓ Valid URL syntax",`Protocol: ${u.protocol.replace(":","")}`,`Host: ${u.host}`,`Path: ${u.pathname||"/"}`,"","Note: a browser-only tool cannot reliably inspect cross-origin redirect chains without a server-side proxy. This tool does not pretend to provide a result it cannot verify."].join("\n"); } catch { return input.trim()?"✕ Invalid URL. Please enter a complete URL such as https://example.com":""; } }
function makeLogo(input: string) { const text=input.trim().slice(0,30); if(!text)return ""; return `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="300" viewBox="0 0 900 300"><rect width="900" height="300" rx="40" fill="#2563eb"/><circle cx="150" cy="150" r="70" fill="#fff"/><text x="270" y="180" font-family="Arial,sans-serif" font-size="82" font-weight="700" fill="#fff">${escapeSvgText(text)}</text></svg>`; }
function run(slug:string,input:string) { if(!input.trim())return ""; switch(slug){ case "ai-text-summarizer":return summarize(input); case "ai-grammar-checker":return grammarCheck(input); case "ai-content-rewriter":return rewriteContent(input); case "ai-headline-generator":return headlineGenerator(input); case "ai-idea-generator":return ideaGenerator(input); case "ai-code-explainer":return explainCode(input); case "url-redirect-checker":return validateRedirectUrl(input); case "logo-maker":return makeLogo(input); default:return input; } }
const AI_SLUGS=new Set(["ai-text-summarizer","ai-grammar-checker","ai-content-rewriter","ai-headline-generator","ai-idea-generator","ai-code-explainer"]);
export default function GenericTool({slug:propSlug}:{slug?:string}) { const {slug:routeSlug}=useParams<{slug:string}>(); const {t}=useTranslation(); const slug=propSlug||routeSlug||""; const tool=getTool(slug); const [input,setInput]=useState(""); const output=useMemo(()=>run(slug,input),[slug,input]); const isLogo=slug==="logo-maker"; const isAI=AI_SLUGS.has(slug); const title=tool?t(tool.nameKey):slug.replace(/-/g," ");
 const placeholder=slug==="ai-code-explainer"?"Paste your code here…":slug==="ai-text-summarizer"?"Paste an article, report, or long text here…":slug==="ai-grammar-checker"?"Paste the text you want to check…":slug==="ai-content-rewriter"?"Paste the text you want to rewrite…":slug==="ai-headline-generator"?"Enter one topic per line…":slug==="ai-idea-generator"?"Enter a topic, niche, or project…":slug==="url-redirect-checker"?"https://example.com":slug==="logo-maker"?"Your brand name":"Type or paste your text here…";
 const helper=isAI?"Private by default: this version processes your input locally in the browser. No text is uploaded by this tool.":slug==="url-redirect-checker"?"Browser-only validation. Cross-origin redirect chains require a server-side request to be verified.":"Your input is processed locally in your browser.";
 return <div className="space-y-5"><ToolIO input={input} onInputChange={setInput} output={output} inputPlaceholder={placeholder} outputPlaceholder={`Your ${title.toLowerCase()} result will appear here…`} downloadName={isLogo?"zidrotool-logo.svg":`${slug}.txt`} inputProps={{spellCheck:slug==="ai-grammar-checker"||slug==="ai-content-rewriter","aria-label":`${title} input`}}/>{isLogo&&output&&<div className="rounded-xl border border-ink-200 bg-ink-50 p-5 dark:border-ink-800 dark:bg-ink-900"><div className="mb-3 text-sm font-medium text-ink-700 dark:text-ink-300">Logo preview</div><div className="overflow-hidden rounded-lg border border-ink-200 bg-white p-4 dark:border-ink-700"><div className="mx-auto max-w-2xl" dangerouslySetInnerHTML={{__html:output}}/></div></div>}<div className={cn("rounded-xl border px-4 py-3 text-sm leading-6",isAI?"border-brand-200 bg-brand-50 text-brand-800 dark:border-brand-900/60 dark:bg-brand-950/40 dark:text-brand-200":"border-ink-200 bg-ink-50 text-ink-600 dark:border-ink-800 dark:bg-ink-900 dark:text-ink-400")}>{helper}</div></div>;
}
export { GenericTool };
