import { useRef, useState } from "react";
import { PDFDocument } from "pdf-lib";
import { Download, FileImage, Loader2, Trash2, Upload } from "lucide-react";
import { downloadBytes } from "@/lib/utils";

function download(bytes: Uint8Array, name: string) {
  downloadBytes(name, bytes, "application/pdf");
}

export default function ImageToPdf() {
  const input=useRef<HTMLInputElement>(null); const [files,setFiles]=useState<File[]>([]); const [busy,setBusy]=useState(false); const [status,setStatus]=useState(""); const [dragging,setDragging]=useState(false);
  const add=(list:FileList|null)=>{if(!list)return; const valid=Array.from(list).filter(f=>/^image\/(png|jpe?g|webp)$/i.test(f.type)); setFiles(x=>[...x,...valid]);};
  const create=async()=>{if(!files.length)return; setBusy(true);setStatus(""); try { const pdf=await PDFDocument.create(); for(const f of files){ const bytes=new Uint8Array(await f.arrayBuffer()); let img:any; if(f.type.includes("png")) img=await pdf.embedPng(bytes); else if(f.type.includes("jpeg")||f.type.includes("jpg")) img=await pdf.embedJpg(bytes); else { const bitmap=await createImageBitmap(f); const canvas=document.createElement("canvas"); canvas.width=bitmap.width;canvas.height=bitmap.height; const ctx=canvas.getContext("2d")!;ctx.drawImage(bitmap,0,0);const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,"image/jpeg",0.92)); if(!blob)throw new Error("WebP conversion failed"); img=await pdf.embedJpg(new Uint8Array(await blob.arrayBuffer())); } const {width,height}=img.scale(1); const page=pdf.addPage([width,height]); page.drawImage(img,{x:0,y:0,width,height}); } download(await pdf.save(),"images-to-pdf.pdf");setStatus(`${files.length} image(s) converted successfully.`);} catch(e){console.error(e);setStatus("Could not create the PDF. Check the image formats.");}finally{setBusy(false)} };
  return <div className="space-y-5"><div className="rounded-2xl border border-ink-200 bg-ink-50/70 p-6 dark:border-ink-800 dark:bg-ink-900/50"><div className="flex items-center gap-3"><FileImage className="h-6 w-6 text-brand-600"/><div><h2 className="font-semibold text-ink-900 dark:text-ink-100">Images to PDF</h2><p className="text-sm text-ink-500">Combine JPG, PNG or WebP images into one PDF.</p></div></div><input ref={input} type="file" multiple accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>add(e.target.files)}/><button type="button" onDragEnter={()=>setDragging(true)} onDragLeave={()=>setDragging(false)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();setDragging(false);add(e.dataTransfer.files)}} onClick={()=>input.current?.click()} className={`mt-5 flex w-full flex-col items-center justify-center gap-2 rounded-xl border-2 border-dashed px-5 py-10 text-sm font-medium transition ${dragging ? "border-brand-500 bg-brand-50" : "border-ink-300 bg-white hover:border-brand-400 dark:border-ink-700 dark:bg-ink-900"}`}><Upload className="h-5 w-5"/><span>Drop images here or click to choose</span><span className="text-xs font-normal text-ink-500">JPG, PNG or WebP</span></button></div>{files.length>0&&<div className="space-y-2">{files.map((f,i)=><div key={`${f.name}-${i}`} className="flex items-center gap-3 rounded-xl border border-ink-200 p-3 dark:border-ink-800"><FileImage className="h-5 w-5 text-brand-500"/><span className="min-w-0 flex-1 truncate text-sm">{f.name}</span><button onClick={()=>setFiles(x=>x.filter((_,n)=>n!==i))} className="text-ink-400 hover:text-danger"><Trash2 className="h-4 w-4"/></button></div>)}<button onClick={create} disabled={busy} className="btn-primary w-full">{busy?<><Loader2 className="h-4 w-4 animate-spin"/>Creating…</>:<><Download className="h-4 w-4"/>Create PDF</>}</button></div>}{status&&<p className="rounded-xl bg-brand-50 p-4 text-sm text-brand-700 dark:bg-brand-950/30 dark:text-brand-300">{status}</p>}</div>;
}
