import { useEffect, useMemo, useState } from "react";
import { Pause, Play, RotateCcw, Volume2 } from "lucide-react";
export default function IntervalTimer({ slug="tabata-timer" }:{slug?:string}){
 const tabata=slug.includes("tabata"); const defaults=useMemo(()=>tabata?{work:20,rest:10,rounds:8}:{work:30,rest:15,rounds:10},[tabata]);
 const [work,setWork]=useState(defaults.work),[rest,setRest]=useState(defaults.rest),[rounds,setRounds]=useState(defaults.rounds),[round,setRound]=useState(1),[phase,setPhase]=useState<"work"|"rest">("work"),[left,setLeft]=useState(defaults.work),[running,setRunning]=useState(false),[sound,setSound]=useState(true);
 useEffect(()=>{if(!running)return;const id=window.setInterval(()=>setLeft(v=>{if(v>1)return v-1;if(phase==="work"){setPhase("rest"); if(sound)beep(); return rest;} if(round>=rounds){setRunning(false); if(sound)beep(); return 0;} setRound(r=>r+1);setPhase("work"); if(sound)beep(); return work;}),1000);return()=>clearInterval(id)},[running,phase,round,rounds,rest,work,sound]);
 function beep(){try{const c=new AudioContext();const o=c.createOscillator();const g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=880;g.gain.value=.08;o.start();o.stop(c.currentTime+.12)}catch{}}
 const reset=()=>{setRunning(false);setRound(1);setPhase("work");setLeft(work)};
 const total=(phase==="work"?work:rest)*rounds; const progress=Math.max(0,Math.min(100,100-(left/(phase==="work"?work:rest))*100));
 return <div className="space-y-6"><div className="rounded-2xl border border-brand-200 bg-brand-50/60 p-4 dark:border-brand-900 dark:bg-brand-950/30"><p className="font-semibold text-ink-900 dark:text-ink-100">{tabata?"Tabata Timer":"Interval Timer"}</p><p className="mt-1 text-sm text-ink-600 dark:text-ink-400">{tabata?"Classic 20 seconds work / 10 seconds rest. Customize it below.":"Customize work, rest and rounds for your interval workout."}</p></div><div className="grid gap-3 sm:grid-cols-3"><label className="label">Work (seconds)<input className="input mt-1" type="number" min="1" value={work} onChange={e=>{const v=Math.max(1,+e.target.value||1);setWork(v);if(!running)setLeft(v)}}/></label><label className="label">Rest (seconds)<input className="input mt-1" type="number" min="0" value={rest} onChange={e=>setRest(Math.max(0,+e.target.value||0))}/></label><label className="label">Rounds<input className="input mt-1" type="number" min="1" value={rounds} onChange={e=>setRounds(Math.max(1,+e.target.value||1))}/></label></div><div className="overflow-hidden rounded-3xl bg-ink-950 p-8 text-center text-white"><p className="text-xs uppercase tracking-[.25em] text-white/50">{phase==="work"?"WORK":"REST"} · ROUND {round}/{rounds}</p><div className="my-4 text-7xl font-black tabular-nums">{String(Math.floor(left/60)).padStart(2,"0")}:{String(left%60).padStart(2,"0")}</div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-brand-400 transition-all" style={{width:`${progress}%`}}/></div><div className="mt-6 flex flex-wrap justify-center gap-3"><button className="btn-primary" onClick={()=>setRunning(x=>!x)}>{running?<><Pause className="h-4 w-4"/>Pause</>:<><Play className="h-4 w-4"/>Start</>}</button><button className="btn-secondary" onClick={reset}><RotateCcw className="h-4 w-4"/>Reset</button><button className="btn-secondary" onClick={()=>setSound(x=>!x)}><Volume2 className="h-4 w-4"/>{sound?"Sound on":"Sound off"}</button></div></div><p className="text-center text-xs text-ink-400">{rounds} rounds · {work}s work · {rest}s rest · browser timer runs locally</p></div>
}
