import { useRef, useState } from "react";
import { Download, FileText, Loader2, PenLine } from "lucide-react";
import { PDFDocument } from "pdf-lib";
import { useTranslation } from "react-i18next";
import { useToast } from "@/components/Toast";
import { downloadBytes } from "@/lib/utils";

const PAGE_W=1240, PAGE_H=1754;
export default function TextToHandwriting(){
 const {t}=useTranslation(); const {error}=useToast(); const canvasRef=useRef<HTMLCanvasElement>(null);
 const [text,setText]=useState(""); const [busy,setBusy]=useState(false); const [font,setFont]=useState("Segoe Print"); const [size,setSize]=useState(30);
 const render=()=>{const c=canvasRef.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;c.width=PAGE_W;c.height=PAGE_H;ctx.fillStyle="#fffdf6";ctx.fillRect(0,0,PAGE_W,PAGE_H);ctx.strokeStyle="#d9e5f0";ctx.lineWidth=2;for(let y=110;y<PAGE_H-70;y+=52){ctx.beginPath();ctx.moveTo(70,y);ctx.lineTo(PAGE_W-70,y);ctx.stroke()}ctx.fillStyle="#243447";ctx.font=`${size}px "${font}", cursive`;ctx.textBaseline="alphabetic";const lines=text.split(/\r?\n/);let y=100;for(const line of lines){const words=line.split(" ");let current="";for(const word of words){const test=current?`${current} ${word}`:word;if(ctx.measureText(test).width>PAGE_W-160){ctx.fillText(current,80,y);y+=52;current=word;}else current=test;}ctx.fillText(current,80,y);y+=52;if(y>PAGE_H-80)break;}};
 const exportPng=()=>{render();const c=canvasRef.current;if(!c)return;const a=document.createElement("a");a.href=c.toDataURL("image/png");a.download="handwritten-note.png";a.click()};
 const exportPdf=async()=>{render();const c=canvasRef.current;if(!c)return;setBusy(true);try{const pdf=await PDFDocument.create();const img=await pdf.embedPng(c.toDataURL("image/png"));const page=pdf.addPage([595,842]);page.drawImage(img,{x:0,y:0,width:595,height:842});const bytes=await pdf.save();downloadBytes("handwritten-note.pdf",bytes,"application/pdf");}catch(e){console.error(e);error(t("tool.error"))}finally{setBusy(false)}};
 return <div className="space-y-5"><div className="grid gap-5 lg:grid-cols-2"><div className="space-y-4"><div><label htmlFor="handwriting-text" className="mb-2 block text-sm font-medium text-ink-700 dark:text-ink-300">{t("tool.handwriting.textLabel")}</label><textarea id="handwriting-text" value={text} onChange={e=>setText(e.target.value)} rows={12} className="input w-full resize-y" placeholder={t("tool.handwriting.placeholder")} /></div><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">{t("tool.handwriting.font")}<select value={font} onChange={e=>setFont(e.target.value)} className="input mt-2 w-full"><option>Segoe Print</option><option>Comic Sans MS</option><option>Bradley Hand</option><option>cursive</option></select></label><label className="text-sm font-medium">{t("tool.handwriting.size")}<input type="range" min="20" max="44" value={size} onChange={e=>setSize(Number(e.target.value))} className="mt-4 w-full" /></label></div><div className="flex flex-wrap gap-2"><button type="button" onClick={render} className="btn-secondary"><PenLine className="h-4 w-4" />{t("tool.handwriting.preview")}</button><button type="button" onClick={exportPng} disabled={!text.trim()} className="btn-primary"><Download className="h-4 w-4" />PNG</button><button type="button" onClick={exportPdf} disabled={!text.trim()||busy} className="btn-primary">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<FileText className="h-4 w-4"/>}PDF</button></div></div><div className="overflow-auto rounded-xl border border-ink-200 bg-ink-100 p-3 dark:border-ink-800 dark:bg-ink-950"><canvas ref={canvasRef} className="mx-auto max-w-full rounded bg-white shadow-sm" /></div></div></div>;
}
